"""create a pitch table

Revision ID: 9a2c5c0cb35d
Revises: 829ce4b2fee3
Create Date: 2021-11-06 20:28:22.774236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2c5c0cb35d'
down_revision = '829ce4b2fee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'user_id')
    # ### end Alembic commands ###
